[package]
name = "abc042"
version = "0.1.0"
authors = ["Takayuki Maeda <41065217+TaKO8Ki@users.noreply.github.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = { version = "=0.3.4", features = ["derive"] }

[profile.release]
lto = true
panic = 'abort'
